### ISSUE TITLE
✨Feat: 동화 삭제 API 쿼리 분석 및 최적화

### ISSUE THREAD

**Issue by pyounani** [DS-StoryTeller/back-end#77]
### 📄 이슈 내용
- 현재 동화 삭제 쿼리가 비정상적으로 많이 발생하고 있음 -> N + 1문제 의심
- 개선의 필요성을 느껴 분석하고 최적화할 예정
```
uri: '/books/delete', method: 'DELETE', 요청 처리 시간: 918.123900 ms, 쿼리 개수: 40, 쿼리 시간: 69.142300 ms
```

### 📑상세 내용
- 동화 삭제 API 호출 시, 삭제하려는 책과 관련된 여러 엔티티에 대해 별도의 쿼리가 발생하는 것을 확인했습니다.
- N + 1 문제로 인해 연관된 데이터에 대해 매번 쿼리가 추가로 발생하고 있으며, 이로 인해 총 40개의 쿼리가 실행되었습니다.
- 이러한 문제를 해결하기 위해 다음과 같은 방법 고려 중
  -  Fetch Join
  - Batch Delete

### ✔ 체크리스트
- [x] : N + 1 문제 확인 및 원인 분석
- [x] : Batch Delete 적용 검토
- [x] : 성능 개선 후 요청 처리 시간 및 쿼리 개수 재측정

**Comment by nnimoyoefoki** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
